# Generated by Django 5.2.6 on 2025-09-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField(max_length=16)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='user.buyer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='user.seller')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showroom', to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('discount', models.FloatField(max_length=16)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_seller', to='user.seller')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_showroom', to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
