# Generated by Django 5.2.6 on 2025-09-17 06:41

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.FloatField(max_length=16)),
                ('seller', models.ManyToManyField(related_name='brands', to='user.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('discount', models.FloatField(max_length=16)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_seller', to='user.seller')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_showroom', to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
