# Generated by Django 5.2.6 on 2025-09-24 05:51

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.FloatField(max_length=16, null=True)),
                ('seller', models.ManyToManyField(blank=True, related_name='brands', to='user.seller')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_showroom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
